/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PharmaProvenance } from "./PharmaProvenance";
export * as factories from "./factories";
export { PharmaProvenance__factory } from "./factories/PharmaProvenance__factory";
