/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface PharmaProvenanceInterface extends utils.Interface {
  functions: {
    "anchorDocument(bytes32,string)": FunctionFragment;
    "documentLedger(bytes32)": FunctionFragment;
    "recordShipment(bytes32,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "anchorDocument"
      | "documentLedger"
      | "recordShipment"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "anchorDocument",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "documentLedger",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "recordShipment",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "documentLedger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordShipment",
    data: BytesLike
  ): Result;

  events: {
    "DocumentAnchored(bytes32,string,uint256)": EventFragment;
    "ShipmentEvent(bytes32,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DocumentAnchored"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ShipmentEvent"): EventFragment;
}

export interface DocumentAnchoredEventObject {
  documentHash: string;
  versionId: string;
  timestamp: BigNumber;
}
export type DocumentAnchoredEvent = TypedEvent<
  [string, string, BigNumber],
  DocumentAnchoredEventObject
>;

export type DocumentAnchoredEventFilter =
  TypedEventFilter<DocumentAnchoredEvent>;

export interface ShipmentEventEventObject {
  shipmentId: string;
  eventType: string;
  timestamp: BigNumber;
}
export type ShipmentEventEvent = TypedEvent<
  [string, string, BigNumber],
  ShipmentEventEventObject
>;

export type ShipmentEventEventFilter = TypedEventFilter<ShipmentEventEvent>;

export interface PharmaProvenance extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PharmaProvenanceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    anchorDocument(
      documentHash: PromiseOrValue<BytesLike>,
      versionId: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    documentLedger(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    recordShipment(
      shipmentId: PromiseOrValue<BytesLike>,
      eventType: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  anchorDocument(
    documentHash: PromiseOrValue<BytesLike>,
    versionId: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  documentLedger(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  recordShipment(
    shipmentId: PromiseOrValue<BytesLike>,
    eventType: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    anchorDocument(
      documentHash: PromiseOrValue<BytesLike>,
      versionId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    documentLedger(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recordShipment(
      shipmentId: PromiseOrValue<BytesLike>,
      eventType: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DocumentAnchored(bytes32,string,uint256)"(
      documentHash?: PromiseOrValue<BytesLike> | null,
      versionId?: null,
      timestamp?: null
    ): DocumentAnchoredEventFilter;
    DocumentAnchored(
      documentHash?: PromiseOrValue<BytesLike> | null,
      versionId?: null,
      timestamp?: null
    ): DocumentAnchoredEventFilter;

    "ShipmentEvent(bytes32,string,uint256)"(
      shipmentId?: PromiseOrValue<BytesLike> | null,
      eventType?: null,
      timestamp?: null
    ): ShipmentEventEventFilter;
    ShipmentEvent(
      shipmentId?: PromiseOrValue<BytesLike> | null,
      eventType?: null,
      timestamp?: null
    ): ShipmentEventEventFilter;
  };

  estimateGas: {
    anchorDocument(
      documentHash: PromiseOrValue<BytesLike>,
      versionId: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    documentLedger(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recordShipment(
      shipmentId: PromiseOrValue<BytesLike>,
      eventType: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    anchorDocument(
      documentHash: PromiseOrValue<BytesLike>,
      versionId: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    documentLedger(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recordShipment(
      shipmentId: PromiseOrValue<BytesLike>,
      eventType: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
