/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  PharmaProvenance,
  PharmaProvenanceInterface,
} from "../PharmaProvenance";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "documentHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "versionId",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "DocumentAnchored",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "shipmentId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "eventType",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ShipmentEvent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "documentHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "versionId",
        type: "string",
      },
    ],
    name: "anchorDocument",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "documentLedger",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "shipmentId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "eventType",
        type: "string",
      },
    ],
    name: "recordShipment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5061038b8061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063512e4d2a14610046578063f0563fdb14610062578063f063420714610092575b600080fd5b610060600480360381019061005b9190610204565b6100ae565b005b61007c60048036038101906100779190610264565b6100ef565b60405161008991906102aa565b60405180910390f35b6100ac60048036038101906100a79190610204565b610107565b005b827fe616a5fe60250f9b5fba12f6f5580b7d68828c3cc8fef067193626dbd8e1f5668383426040516100e293929190610323565b60405180910390a2505050565b60006020528060005260406000206000915090505481565b4260008085815260200190815260200160002081905550827f37d4362d854816a8f06e69fe68a37e9ca2288dcb3fb2884b5e4e6fcfc74c2c0a83834260405161015293929190610323565b60405180910390a2505050565b600080fd5b600080fd5b6000819050919050565b61017c81610169565b811461018757600080fd5b50565b60008135905061019981610173565b92915050565b600080fd5b600080fd5b600080fd5b60008083601f8401126101c4576101c361019f565b5b8235905067ffffffffffffffff8111156101e1576101e06101a4565b5b6020830191508360018202830111156101fd576101fc6101a9565b5b9250929050565b60008060006040848603121561021d5761021c61015f565b5b600061022b8682870161018a565b935050602084013567ffffffffffffffff81111561024c5761024b610164565b5b610258868287016101ae565b92509250509250925092565b60006020828403121561027a5761027961015f565b5b60006102888482850161018a565b91505092915050565b6000819050919050565b6102a481610291565b82525050565b60006020820190506102bf600083018461029b565b92915050565b600082825260208201905092915050565b82818337600083830152505050565b6000601f19601f8301169050919050565b600061030283856102c5565b935061030f8385846102d6565b610318836102e5565b840190509392505050565b6000604082019050818103600083015261033e8185876102f6565b905061034d602083018461029b565b94935050505056fea264697066735822122040b503e0be3924eb556de5e81aab37e029defb7878e0a70535b94efcf180221764736f6c634300081b0033";

type PharmaProvenanceConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PharmaProvenanceConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PharmaProvenance__factory extends ContractFactory {
  constructor(...args: PharmaProvenanceConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<PharmaProvenance> {
    return super.deploy(overrides || {}) as Promise<PharmaProvenance>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PharmaProvenance {
    return super.attach(address) as PharmaProvenance;
  }
  override connect(signer: Signer): PharmaProvenance__factory {
    return super.connect(signer) as PharmaProvenance__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PharmaProvenanceInterface {
    return new utils.Interface(_abi) as PharmaProvenanceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PharmaProvenance {
    return new Contract(address, _abi, signerOrProvider) as PharmaProvenance;
  }
}
